# Copyright the Hyperledger Fabric contributors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: $(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.rrr)
trigger: none
pr:
- master
- release-2.*

variables:
  GOPATH: $(Agent.BuildDirectory)/go
  PATH: $(Agent.BuildDirectory)/go/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin
  GOVER: 1.14.4
  PKCS11_LIB: /usr/local/Cellar/softhsm/2.6.1/lib/softhsm/libsofthsm2.so
  PKCS11_PIN: 98765432
  PKCS11_LABEL: ForFabric

stages:
  - stage: UnitTests
    jobs:
      - job: UnitTests
        pool:
          vmImage: macOS-10.14
        steps:
          - template: install_deps.yml
          - checkout: self
            path: 'fabric'
            displayName: Checkout Fabric Code
          - script: ./ci/scripts/setup_hsm.sh
            displayName: Install SoftHSM
          - script: cd bccsp && go test -tags pkcs11 ./...
            displayName: Run Unit Tests
